name 'example42-tp'
version '0.0.2'

author 'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source 'https://github.com/example42/puppet-tp'
summary 'Tiny Puppet: One module to rule them all'
description 'This module allows the complement management of package, service and file rsources related to the supported. It provides quick, easy to use and consistent defines to manage component applications resources. It also provided a Puppet face to query the provided resources'
#dependency 'puppetlabs/vcsrepo', '>=0.0.1'
#dependency 'puppetlabs/concat', '>=0.0.1'
dependency 'puppetlabs/stdlib', '>=0.0.1'
