name 'example42-tp'
version '0.1.0'

author 'Alessandro Franceschi'
license 'Apache2'
project_page 'https://github.com/example42/puppet-tp'
source 'https://github.com/example42/puppet-tp'
summary 'Tiny Puppet: Yet Another Puppet Abstraction Layer'
description 'This module provides quick, easy to use and consistent defines to install and configure applications resources.'
#dependency 'puppetlabs/vcsrepo', '>=0.0.1'
#dependency 'puppetlabs/concat', '>=0.0.1'
#dependency 'example42/puppi'
dependency 'puppetlabs/stdlib', '>= 3.2.0 < 5.0.0'
