name 'example42-tp'
version '0.1.0-beta4'

author 'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source 'https://github.com/example42/puppet-tp'
summary 'Tiny Puppet: One module to rule them all'
description 'Yet Another Puppet Abstraction Layer. This module provides quick, easy to use and consistent defines to install an configur applications resources. It also provided a Puppet face to query the provided resources'
#dependency 'puppetlabs/vcsrepo', '>=0.0.1'
#dependency 'puppetlabs/concat', '>=0.0.1'
#dependency 'example42/puppi'
dependency 'puppetlabs/stdlib'
