---
name: PR tests

on: pull_request

jobs:
  static:
    name: 'Static code analysys'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Setup puppet-dev-tools image
        uses: puppet/puppet-dev-tools:4.x
        run: pdk validate

  unit:
    needs: static
    name: 'Unit tests'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Setup puppet-dev-tools image
        uses: puppet/puppet-dev-tools:4.x
        run: pdk test unit

