---
name: PR tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  static:
    name: 'Static code analysys'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Run pdk validate
        uses: puppet-enterprise-support-team/action-pdk-validate@v1
  unit:
    needs: static
    name: 'Unit tests'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Run unit tests
        uses: puppet-enterprise-support-team/action-pdk-test-unit@v1
