---
name: PR tests

on: pull_request

jobs:
  static:
    name: 'Static code analysys'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      BUNDLE_WITHOUT: development:system_tests:release
    steps:
      - uses: actions/checkout@v2
      - name: Run static validations
        uses: puppet/puppet-dev-tools:4.x
        run: pdk bundle exec rake validate lint check
  unit:
    name: 'Unit tests'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      BUNDLE_WITHOUT: development:system_tests:release
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        uses: puppet/puppet-dev-tools:4.x
        run: pdk bundle exec rake spec
