---
name: PR tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  static:
    name: 'Static code analysys'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Setup puppet-dev-tools image
        uses: puppet/puppet-dev-tools:4.x-rootless
      - name: Run pdk validate
        run: pdk validate
  unit:
    needs: static
    name: 'Unit tests'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Setup puppet-dev-tools image
        uses: puppet/puppet-dev-tools:4.x-rootless
      - name: Run pdk test unit
        run: pdk test unit

